import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface ReportData {
  id: string
  title: string
  description: string | null
  type: 'ANALYTICS' | 'FINANCIAL' | 'ACADEMIC' | 'USER_ACTIVITY' | 'SYSTEM_HEALTH' | 'CUSTOM'
  status: 'DRAFT' | 'GENERATING' | 'COMPLETED' | 'FAILED' | 'EXPIRED'
  content: string
  filters: string | null
  isPublic: boolean
  scheduledAt: string | null
  expiresAt: string | null
  createdAt: string
  updatedAt: string
  generatedByUser: {
    id: string
    firstName: string
    lastName: string
    email: string
  }
  school: {
    id: string
    name: string
    email: string
    address: string
    phone: string
  } | null
}

export class PDFGenerator {
  private doc: jsPDF

  constructor() {
    this.doc = new jsPDF()
  }

  generateReportPDF(reportData: ReportData): void {
    const { doc } = this
    
    // Set up the document
    doc.setProperties({
      title: reportData.title,
      subject: `Report - ${reportData.type}`,
      author: `${reportData.generatedByUser.firstName} ${reportData.generatedByUser.lastName}`,
      creator: 'EduGenius AI',
      keywords: 'report, education, analytics',
    })

    // Add header
    this.addHeader(reportData)
    
    // Add report information
    this.addReportInfo(reportData)
    
    // Add content
    this.addContent(reportData)
    
    // Add footer
    this.addFooter(reportData)
    
    // Save the PDF
    const fileName = `${reportData.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(fileName)
  }

  private addHeader(reportData: ReportData): void {
    const { doc } = this
    
    // Logo area (placeholder)
    doc.setFillColor(59, 130, 246) // Blue color
    doc.rect(20, 20, 170, 25, 'F')
    
    // Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('EduGenius AI', 25, 35)
    
    // Report title
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(reportData.title, 20, 60)
    
    // Report type and status
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Type: ${reportData.type.replace('_', ' ')}`, 20, 70)
    doc.text(`Status: ${reportData.status}`, 20, 75)
    
    // Generated date
    doc.text(`Generated: ${new Date(reportData.createdAt).toLocaleDateString()}`, 20, 80)
    
    // Line separator
    doc.setDrawColor(200, 200, 200)
    doc.line(20, 85, 190, 85)
  }

  private addReportInfo(reportData: ReportData): void {
    const { doc } = this
    let yPosition = 95
    
    // Report Information Section
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(59, 130, 246)
    doc.text('Report Information', 20, yPosition)
    yPosition += 10
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    
    // Description
    if (reportData.description) {
      doc.text('Description:', 20, yPosition)
      yPosition += 5
      const description = doc.splitTextToSize(reportData.description, 170)
      doc.text(description, 20, yPosition)
      yPosition += description.length * 4 + 5
    }
    
    // Generated by
    doc.text(`Generated by: ${reportData.generatedByUser.firstName} ${reportData.generatedByUser.lastName}`, 20, yPosition)
    yPosition += 5
    
    // School information
    if (reportData.school) {
      doc.text(`School: ${reportData.school.name}`, 20, yPosition)
      yPosition += 5
      doc.text(`Email: ${reportData.school.email}`, 20, yPosition)
      yPosition += 5
      if (reportData.school.address) {
        doc.text(`Address: ${reportData.school.address}`, 20, yPosition)
        yPosition += 5
      }
      if (reportData.school.phone) {
        doc.text(`Phone: ${reportData.school.phone}`, 20, yPosition)
        yPosition += 5
      }
    }
    
    // Public/Private status
    doc.text(`Access: ${reportData.isPublic ? 'Public' : 'Private'}`, 20, yPosition)
    yPosition += 5
    
    // Scheduling information
    if (reportData.scheduledAt) {
      doc.text(`Scheduled: ${new Date(reportData.scheduledAt).toLocaleString()}`, 20, yPosition)
      yPosition += 5
    }
    
    if (reportData.expiresAt) {
      doc.text(`Expires: ${new Date(reportData.expiresAt).toLocaleString()}`, 20, yPosition)
      yPosition += 5
    }
    
    yPosition += 10
    doc.setDrawColor(200, 200, 200)
    doc.line(20, yPosition, 190, yPosition)
    yPosition += 10
  }

  private addContent(reportData: ReportData): void {
    const { doc } = this
    let yPosition = 95
    
    // Find the last position from report info
    yPosition = this.findLastYPosition() + 20
    
    // Report Content Section
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(59, 130, 246)
    doc.text('Report Content', 20, yPosition)
    yPosition += 10
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    
    // Parse and display content
    try {
      const content = JSON.parse(reportData.content)
      const contentText = JSON.stringify(content, null, 2)
      const contentLines = doc.splitTextToSize(contentText, 170)
      
      // Check if content fits on current page
      if (yPosition + (contentLines.length * 4) > 250) {
        doc.addPage()
        yPosition = 20
      }
      
      doc.text(contentLines, 20, yPosition)
      yPosition += contentLines.length * 4 + 10
    } catch (error) {
      doc.text('Content could not be parsed as JSON', 20, yPosition)
      yPosition += 10
    }
    
    // Filters
    if (reportData.filters) {
      yPosition += 10
      doc.setFont('helvetica', 'bold')
      doc.text('Filters Applied:', 20, yPosition)
      yPosition += 5
      
      doc.setFont('helvetica', 'normal')
      try {
        const filters = JSON.parse(reportData.filters)
        const filterText = JSON.stringify(filters, null, 2)
        const filterLines = doc.splitTextToSize(filterText, 170)
        
        // Check if filters fit on current page
        if (yPosition + (filterLines.length * 4) > 250) {
          doc.addPage()
          yPosition = 20
        }
        
        doc.text(filterLines, 20, yPosition)
      } catch (error) {
        doc.text('Filters could not be parsed as JSON', 20, yPosition)
      }
    }
  }

  private addFooter(reportData: ReportData): void {
    const { doc } = this
    const pageCount = doc.getNumberOfPages()
    
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      
      // Footer line
      doc.setDrawColor(200, 200, 200)
      doc.line(20, 280, 190, 280)
      
      // Footer text
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 100, 100)
      
      // Left side
      doc.text(`EduGenius AI Report - ${reportData.title}`, 20, 285)
      
      // Right side
      doc.text(`Page ${i} of ${pageCount}`, 170, 285)
      
      // Bottom right
      doc.text(`Generated on ${new Date().toLocaleString()}`, 20, 290)
    }
  }

  private findLastYPosition(): number {
    // This is a simplified method - in a real implementation,
    // you'd track the Y position as you add content
    return 150
  }
}

export const generateReportPDF = (reportData: ReportData): void => {
  const generator = new PDFGenerator()
  generator.generateReportPDF(reportData)
}
