// Enhanced Presentation Generator with AI Images
import PptxGenJS from 'pptxgenjs'
import { imageGenerationService } from './image-generation'

export interface PresentationSlide {
  title: string
  content: string[]
  notes?: string
  imagePrompt?: string
  layout?: 'title' | 'content' | 'image' | 'split'
}

export interface PresentationRequest {
  title: string
  subtitle?: string
  author?: string
  slides: PresentationSlide[]
  theme?: 'education' | 'modern' | 'professional'
  generateImages?: boolean
  imageStyle?: 'educational' | 'diagram' | 'natural' | 'vivid'
}

export class PresentationGenerator {
  private pptx: PptxGenJS

  constructor() {
    this.pptx = new PptxGenJS()
  }

  /**
   * Generate a complete presentation with AI-generated images
   */
  async generatePresentation(request: PresentationRequest): Promise<Buffer> {
    // Set presentation properties
    this.pptx.author = request.author || 'ElimuNova AI'
    this.pptx.title = request.title
    this.pptx.subject = 'Educational Presentation'
    this.pptx.company = 'ElimuNova AI'

    // Apply theme
    this.applyTheme(request.theme || 'education')

    // Add title slide
    this.addTitleSlide(request.title, request.subtitle)

    // Generate images if requested
    let generatedImages: Map<number, string> = new Map()
    
    if (request.generateImages) {
      generatedImages = await this.generateSlideImages(request.slides, request.imageStyle)
    }

    // Add content slides
    for (let i = 0; i < request.slides.length; i++) {
      const slide = request.slides[i]
      const imageUrl = generatedImages.get(i)

      await this.addContentSlide(slide, imageUrl)
    }

    // Generate and return buffer
    const buffer = await this.pptx.write({ outputType: 'nodebuffer' }) as Buffer
    return buffer
  }

  /**
   * Generate images for slides that need them
   */
  private async generateSlideImages(slides: PresentationSlide[], style?: string): Promise<Map<number, string>> {
    const imageMap = new Map<number, string>()

    for (let i = 0; i < slides.length; i++) {
      const slide = slides[i]
      
      if (slide.imagePrompt || slide.layout === 'image' || slide.layout === 'split') {
        try {
          const prompt = slide.imagePrompt || `Educational illustration for: ${slide.title}`
          
          console.log(`Generating image for slide ${i + 1}: ${prompt}`)
          
          const result = await imageGenerationService.generateImage({
            prompt,
            style: (style as any) || 'educational',
            size: '1024x1024',
            quality: 'standard'
          })

          imageMap.set(i, result.url)
        } catch (error) {
          console.error(`Failed to generate image for slide ${i + 1}:`, error)
          // Continue without image
        }
      }
    }

    return imageMap
  }

  /**
   * Apply theme to presentation
   */
  private applyTheme(theme: string) {
    const themes = {
      education: {
        background: { color: 'FFFFFF' },
        titleColor: '2E5090',
        textColor: '333333',
        accentColor: '4472C4'
      },
      modern: {
        background: { color: 'F5F5F5' },
        titleColor: '1F1F1F',
        textColor: '424242',
        accentColor: '00BCD4'
      },
      professional: {
        background: { color: 'FFFFFF' },
        titleColor: '1A237E',
        textColor: '212121',
        accentColor: '3F51B5'
      }
    }

    const selectedTheme = themes[theme as keyof typeof themes] || themes.education
    this.pptx.defineLayout({ name: 'CUSTOM', width: 10, height: 5.625 })
    this.pptx.layout = 'CUSTOM'
  }

  /**
   * Add title slide
   */
  private addTitleSlide(title: string, subtitle?: string) {
    const slide = this.pptx.addSlide()

    // Background
    slide.background = { color: '2E5090' }

    // Title
    slide.addText(title, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 1.5,
      fontSize: 44,
      bold: true,
      color: 'FFFFFF',
      align: 'center',
      valign: 'middle'
    })

    // Subtitle
    if (subtitle) {
      slide.addText(subtitle, {
        x: 0.5,
        y: 3.2,
        w: 9,
        h: 0.8,
        fontSize: 24,
        color: 'E0E0E0',
        align: 'center',
        valign: 'middle'
      })
    }

    // Footer
    slide.addText('Generated by ElimuNova AI', {
      x: 0.5,
      y: 5,
      w: 9,
      h: 0.4,
      fontSize: 12,
      color: 'CCCCCC',
      align: 'center'
    })
  }

  /**
   * Add content slide with optional image
   */
  private async addContentSlide(slideData: PresentationSlide, imageUrl?: string) {
    const slide = this.pptx.addSlide()

    // Background
    slide.background = { color: 'FFFFFF' }

    const layout = slideData.layout || 'content'

    if (layout === 'image' && imageUrl) {
      // Full image slide
      slide.addText(slideData.title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.6,
        fontSize: 32,
        bold: true,
        color: '2E5090'
      })

      slide.addImage({
        data: imageUrl,
        x: 1,
        y: 1.2,
        w: 8,
        h: 4
      })

    } else if (layout === 'split' && imageUrl) {
      // Split layout: content on left, image on right
      slide.addText(slideData.title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.6,
        fontSize: 32,
        bold: true,
        color: '2E5090'
      })

      // Content on left
      const bulletPoints = slideData.content.map(item => ({ text: item, options: { bullet: true } }))
      slide.addText(bulletPoints, {
        x: 0.5,
        y: 1.2,
        w: 4.5,
        h: 3.8,
        fontSize: 16,
        color: '333333'
      })

      // Image on right
      slide.addImage({
        data: imageUrl,
        x: 5.2,
        y: 1.2,
        w: 4.3,
        h: 3.8
      })

    } else {
      // Standard content slide
      slide.addText(slideData.title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.6,
        fontSize: 32,
        bold: true,
        color: '2E5090'
      })

      // Add content as bullet points
      const bulletPoints = slideData.content.map(item => ({ text: item, options: { bullet: true } }))
      slide.addText(bulletPoints, {
        x: 0.5,
        y: 1.2,
        w: imageUrl ? 5 : 9,
        h: 3.8,
        fontSize: 18,
        color: '333333'
      })

      // Add small image if available
      if (imageUrl) {
        slide.addImage({
          data: imageUrl,
          x: 6,
          y: 1.5,
          w: 3.5,
          h: 3.5
        })
      }
    }

    // Add notes if provided
    if (slideData.notes) {
      slide.addNotes(slideData.notes)
    }

    // Add slide number
    const slideCount = (this.pptx as any).slides?.length || 1
    slide.addText(`${slideCount}`, {
      x: 9.2,
      y: 5.2,
      w: 0.5,
      h: 0.3,
      fontSize: 10,
      color: '999999',
      align: 'right'
    })
  }

  /**
   * Generate presentation from AI content
   */
  static async generateFromAIContent(
    title: string,
    content: string,
    options?: {
      generateImages?: boolean
      imageStyle?: string
      theme?: string
    }
  ): Promise<Buffer> {
    const generator = new PresentationGenerator()

    // Parse content into slides
    const slides = this.parseContentIntoSlides(content)

    return await generator.generatePresentation({
      title,
      subtitle: 'Generated by ElimuNova AI',
      author: 'ElimuNova AI',
      slides,
      theme: (options?.theme as any) || 'education',
      generateImages: options?.generateImages || false,
      imageStyle: (options?.imageStyle as any) || 'educational'
    })
  }

  /**
   * Parse markdown/text content into slides
   */
  private static parseContentIntoSlides(content: string): PresentationSlide[] {
    const slides: PresentationSlide[] = []
    
    // Split by headers (## or ###)
    const sections = content.split(/(?=^#{2,3}\s)/m)

    for (const section of sections) {
      if (!section.trim()) continue

      const lines = section.trim().split('\n')
      const titleLine = lines[0]
      
      // Extract title
      const title = titleLine.replace(/^#{2,3}\s*/, '').trim()
      
      // Extract content (bullet points or paragraphs)
      const contentLines = lines.slice(1)
        .filter(line => line.trim())
        .map(line => line.replace(/^[-*]\s*/, '').trim())
        .filter(line => line.length > 0)

      if (title && contentLines.length > 0) {
        slides.push({
          title,
          content: contentLines,
          layout: 'content'
        })
      }
    }

    return slides
  }
}

export const presentationGenerator = new PresentationGenerator()
