// Comprehensive list of subjects for the EduGenius platform
// This includes all subjects from the lesson plan creation form plus additional academic subjects

export const COMPREHENSIVE_SUBJECTS = [
  // Core Curriculum Subjects (from lesson plan creation)
  'Mathematics',
  'English',
  'Integrated Science',
  'Pretechnical Studies',
  'Kiswahili',
  'Christian Religious Education',
  'Science and Technology',
  'Creative Arts',
  'Social Studies',
  'Agriculture',
  'History',
  'Geography',
  'Physical Education',
  'French',
  'German',
  'Spanish',
  'Arabic',
  'Computer Studies',
  'Business Studies',
  'Economics',
  
  // Additional Academic Subjects
  'Physics',
  'Chemistry',
  'Biology',
  'Art',
  'Music',
  'Religious Studies',
  'Civics',
  'Environmental Studies',
  'Home Science',
  'Technical Drawing',
  'Woodwork',
  'Metalwork',
  'Electrical Installation',
  'Building Construction',
  'Food and Nutrition',
  'Clothing and Textiles',
  'Fine Art',
  'Drama',
  'Dance',
  'Literature',
  'Linguistics',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Political Science',
  'Anthropology',
  'Archaeology',
  'Astronomy',
  'Geology',
  'Meteorology',
  'Oceanography',
  'Botany',
  'Zoology',
  'Anatomy',
  'Physiology',
  'Genetics',
  'Ecology',
  'Biotechnology',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Cybersecurity',
  'Digital Marketing',
  'Accounting',
  'Finance',
  'Banking',
  'Insurance',
  'Real Estate',
  'Tourism',
  'Hospitality',
  'Culinary Arts',
  'Event Management',
  'Sports Science',
  'Health Education',
  'First Aid',
  'Nursing',
  'Medicine',
  'Pharmacy',
  'Dentistry',
  'Veterinary Science',
  'Engineering',
  'Architecture',
  'Urban Planning',
  'Landscape Design',
  'Interior Design',
  'Fashion Design',
  'Graphic Design',
  'Web Design',
  'Animation',
  'Photography',
  'Film Studies',
  'Media Studies',
  'Journalism',
  'Communication',
  'Public Relations',
  'Advertising',
  'Marketing',
  'Sales',
  'Human Resources',
  'Management',
  'Leadership',
  'Entrepreneurship',
  'Innovation',
  'Project Management',
  'Quality Assurance',
  'Logistics',
  'Supply Chain',
  'Operations',
  'Research Methods',
  'Statistics',
  'Data Analysis',
  'Machine Learning',
  'Artificial Intelligence',
  'Robotics',
  'Automation',
  'Blockchain',
  'Cryptocurrency',
  'E-commerce',
  'Digital Transformation',
  'Sustainability',
  'Environmental Science',
  'Climate Change',
  'Renewable Energy',
  'Green Technology',
  'Conservation',
  'Wildlife Management',
  'Forestry',
  'Marine Biology',
  'Aquaculture',
  'Food Science',
  'Nutrition',
  'Dietetics',
  'Public Health',
  'Epidemiology',
  'Global Health',
  'Mental Health',
  'Counseling',
  'Social Work',
  'Community Development',
  'International Relations',
  'Diplomacy',
  'Law',
  'Legal Studies',
  'Criminology',
  'Forensic Science',
  'Security Studies',
  'Military Science',
  'Peace Studies',
  'Conflict Resolution',
  'Human Rights',
  'Gender Studies',
  'Cultural Studies',
  'Ethnic Studies',
  'Indigenous Studies',
  'African Studies',
  'Asian Studies',
  'European Studies',
  'American Studies',
  'Middle Eastern Studies',
  'Latin American Studies',
  'Caribbean Studies',
  'Development Studies',
  'Urban Studies',
  'Rural Studies',
  'Migration Studies',
  'Refugee Studies',
  'Disability Studies',
  'Aging Studies',
  'Youth Studies',
  'Family Studies',
  'Child Development',
  'Education',
  'Pedagogy',
  'Curriculum Studies',
  'Educational Psychology',
  'Special Education',
  'Adult Education',
  'Distance Learning',
  'E-learning',
  'Educational Technology',
  'Learning Analytics',
  'Assessment',
  'Evaluation',
  'Testing',
  'Measurement',
  'Psychometrics',
  'Cognitive Science',
  'Neuroscience',
  'Behavioral Science',
  'Social Psychology',
  'Developmental Psychology',
  'Educational Neuroscience',
  'Learning Sciences',
  'Instructional Design',
  'Training and Development',
  'Organizational Behavior',
  'Industrial Psychology',
  'Consumer Psychology',
  'Sports Psychology',
  'Health Psychology',
  'Clinical Psychology',
  'Counseling Psychology',
  'School Psychology',
  'Forensic Psychology',
  'Environmental Psychology',
  'Cross-cultural Psychology',
  'Positive Psychology',
  'Applied Psychology',
  'Experimental Psychology',
  'Theoretical Psychology',
  'Philosophy of Mind',
  'Ethics',
  'Logic',
  'Critical Thinking',
  'Argumentation',
  'Rhetoric',
  'Composition',
  'Creative Writing',
  'Technical Writing',
  'Academic Writing',
  'Research Writing',
  'Grant Writing',
  'Proposal Writing',
  'Report Writing',
  'Business Writing',
  'Professional Writing',
  'Copywriting',
  'Content Writing',
  'Scriptwriting',
  'Screenwriting',
  'Playwriting',
  'Poetry',
  'Fiction',
  'Non-fiction',
  'Biography',
  'Autobiography',
  'Memoir',
  'Travel Writing',
  'Food Writing',
  'Sports Writing',
  'Science Writing',
  'Medical Writing',
  'Legal Writing',
  'Technical Communication',
  'User Experience Writing',
  'Content Strategy',
  'Editorial',
  'Publishing',
  'Book Design',
  'Typography',
  'Layout Design',
  'Print Design',
  'Packaging Design',
  'Brand Design',
  'Logo Design',
  'Identity Design',
  'Environmental Design',
  'Exhibition Design',
  'Museum Design',
  'Retail Design',
  'Restaurant Design',
  'Hotel Design',
  'Residential Design',
  'Commercial Design',
  'Industrial Design',
  'Product Design',
  'Furniture Design',
  'Lighting Design',
  'Textile Design',
  'Surface Design',
  'Pattern Design',
  'Color Theory',
  'Design History',
  'Design Theory',
  'Design Thinking',
  'Design Research',
  'User Research',
  'Market Research',
  'Consumer Research',
  'Design Strategy',
  'Design Management',
  'Design Leadership',
  'Design Innovation',
  'Design Technology',
  'Digital Design',
  'Interactive Design',
  'Experience Design',
  'Service Design',
  'Systems Design',
  'Information Design',
  'Data Visualization',
  'Infographic Design',
  'Chart Design',
  'Diagram Design',
  'Map Design',
  'Wayfinding Design',
  'Signage Design',
  'Environmental Graphics',
  'Exhibition Graphics',
  'Museum Graphics',
  'Retail Graphics',
  'Restaurant Graphics',
  'Hotel Graphics',
  'Office Graphics',
  'Corporate Graphics',
  'Institutional Graphics',
  'Government Graphics',
  'Non-profit Graphics',
  'Educational Graphics',
  'Healthcare Graphics',
  'Financial Graphics',
  'Technology Graphics',
  'Entertainment Graphics',
  'Sports Graphics',
  'Fashion Graphics',
  'Beauty Graphics',
  'Food Graphics',
  'Travel Graphics',
  'Automotive Graphics',
  'Aerospace Graphics',
  'Marine Graphics',
  'Architectural Graphics',
  'Engineering Graphics',
  'Scientific Graphics',
  'Medical Graphics',
  'Legal Graphics',
  'Political Graphics',
  'Social Graphics',
  'Cultural Graphics',
  'Historical Graphics',
  'Geographic Graphics',
  'Geological Graphics',
  'Meteorological Graphics',
  'Astronomical Graphics',
  'Biological Graphics',
  'Chemical Graphics',
  'Physical Graphics',
  'Mathematical Graphics',
  'Statistical Graphics',
  'Economic Graphics',
  'Financial Graphics',
  'Business Graphics',
  'Marketing Graphics',
  'Advertising Graphics',
  'Promotional Graphics',
  'Event Graphics',
  'Conference Graphics',
  'Seminar Graphics',
  'Workshop Graphics',
  'Training Graphics',
  'Educational Graphics',
  'Instructional Graphics',
  'Tutorial Graphics',
  'How-to Graphics',
  'Step-by-step Graphics',
  'Process Graphics',
  'Workflow Graphics',
  'System Graphics',
  'Network Graphics',
  'Database Graphics',
  'Software Graphics',
  'App Graphics',
  'Website Graphics',
  'Interface Graphics',
  'User Interface Graphics',
  'User Experience Graphics',
  'Mobile Graphics',
  'Desktop Graphics',
  'Web Graphics',
  'Print Graphics',
  'Digital Graphics',
  'Vector Graphics',
  'Raster Graphics',
  '3D Graphics',
  'Animation Graphics',
  'Motion Graphics',
  'Video Graphics',
  'Film Graphics',
  'Television Graphics',
  'Broadcast Graphics',
  'Streaming Graphics',
  'Social Media Graphics',
  'Platform Graphics',
  'Content Graphics',
  'Editorial Graphics',
  'Publishing Graphics',
  'Book Graphics',
  'Magazine Graphics',
  'Newspaper Graphics',
  'Journal Graphics',
  'Academic Graphics',
  'Research Graphics',
  'Scientific Graphics',
  'Technical Graphics',
  'Engineering Graphics',
  'Architectural Graphics',
  'Construction Graphics',
  'Manufacturing Graphics',
  'Industrial Graphics',
  'Commercial Graphics',
  'Retail Graphics',
  'Wholesale Graphics',
  'Distribution Graphics',
  'Logistics Graphics',
  'Supply Chain Graphics',
  'Operations Graphics',
  'Management Graphics',
  'Leadership Graphics',
  'Strategy Graphics',
  'Planning Graphics',
  'Project Graphics',
  'Program Graphics',
  'Portfolio Graphics',
  'Investment Graphics',
  'Financial Graphics',
  'Accounting Graphics',
  'Auditing Graphics',
  'Tax Graphics',
  'Insurance Graphics',
  'Banking Graphics',
  'Credit Graphics',
  'Loan Graphics',
  'Mortgage Graphics',
  'Real Estate Graphics',
  'Property Graphics',
  'Development Graphics',
  'Construction Graphics',
  'Architecture Graphics',
  'Engineering Graphics',
  'Design Graphics',
  'Planning Graphics',
  'Zoning Graphics',
  'Permit Graphics',
  'Inspection Graphics',
  'Safety Graphics',
  'Security Graphics',
  'Emergency Graphics',
  'Disaster Graphics',
  'Crisis Graphics',
  'Risk Graphics',
  'Compliance Graphics',
  'Regulatory Graphics',
  'Legal Graphics',
  'Court Graphics',
  'Law Graphics',
  'Justice Graphics',
  'Crime Graphics',
  'Forensic Graphics',
  'Investigation Graphics',
  'Evidence Graphics',
  'Witness Graphics',
  'Testimony Graphics',
  'Trial Graphics',
  'Verdict Graphics',
  'Sentencing Graphics',
  'Prison Graphics',
  'Corrections Graphics',
  'Rehabilitation Graphics',
  'Probation Graphics',
  'Parole Graphics',
  'Community Graphics',
  'Social Graphics',
  'Welfare Graphics',
  'Health Graphics',
  'Medical Graphics',
  'Dental Graphics',
  'Mental Graphics',
  'Therapy Graphics',
  'Counseling Graphics',
  'Treatment Graphics',
  'Recovery Graphics',
  'Rehabilitation Graphics',
  'Disability Graphics',
  'Accessibility Graphics',
  'Inclusion Graphics',
  'Diversity Graphics',
  'Equity Graphics',
  'Justice Graphics',
  'Rights Graphics',
  'Freedoms Graphics',
  'Liberties Graphics',
  'Democracy Graphics',
  'Government Graphics',
  'Politics Graphics',
  'Elections Graphics',
  'Voting Graphics',
  'Campaign Graphics',
  'Candidates Graphics',
  'Parties Graphics',
  'Platforms Graphics',
  'Policies Graphics',
  'Programs Graphics',
  'Initiatives Graphics',
  'Referendums Graphics',
  'Amendments Graphics',
  'Constitution Graphics',
  'Laws Graphics',
  'Regulations Graphics',
  'Rules Graphics',
  'Standards Graphics',
  'Guidelines Graphics',
  'Procedures Graphics',
  'Protocols Graphics',
  'Policies Graphics',
  'Agreements Graphics',
  'Treaties Graphics',
  'Contracts Graphics',
  'Negotiations Graphics',
  'Mediation Graphics',
  'Arbitration Graphics',
  'Resolution Graphics',
  'Settlement Graphics',
  'Compromise Graphics',
  'Consensus Graphics',
  'Collaboration Graphics',
  'Cooperation Graphics',
  'Partnership Graphics',
  'Alliance Graphics',
  'Coalition Graphics',
  'Federation Graphics',
  'Confederation Graphics',
  'Union Graphics',
  'Association Graphics',
  'Organization Graphics',
  'Institution Graphics',
  'Agency Graphics',
  'Department Graphics',
  'Ministry Graphics',
  'Bureau Graphics',
  'Office Graphics',
  'Center Graphics',
  'Institute Graphics',
  'Foundation Graphics',
  'Trust Graphics',
  'Fund Graphics',
  'Endowment Graphics',
  'Grant Graphics',
  'Scholarship Graphics',
  'Fellowship Graphics',
  'Award Graphics',
  'Recognition Graphics',
  'Honor Graphics',
  'Achievement Graphics',
  'Success Graphics',
  'Excellence Graphics',
  'Quality Graphics',
  'Performance Graphics',
  'Productivity Graphics',
  'Efficiency Graphics',
  'Effectiveness Graphics',
  'Impact Graphics',
  'Outcome Graphics',
  'Result Graphics',
  'Consequence Graphics',
  'Benefit Graphics',
  'Value Graphics',
  'Worth Graphics',
  'Cost Graphics',
  'Price Graphics',
  'Fee Graphics',
  'Charge Graphics',
  'Rate Graphics',
  'Tariff Graphics',
  'Duty Graphics',
  'Tax Graphics',
  'Levy Graphics',
  'Assessment Graphics',
  'Evaluation Graphics',
  'Appraisal Graphics',
  'Valuation Graphics',
  'Estimation Graphics',
  'Calculation Graphics',
  'Computation Graphics',
  'Analysis Graphics',
  'Synthesis Graphics',
  'Integration Graphics',
  'Coordination Graphics',
  'Management Graphics',
  'Administration Graphics',
  'Governance Graphics',
  'Leadership Graphics',
  'Direction Graphics',
  'Guidance Graphics',
  'Supervision Graphics',
  'Oversight Graphics',
  'Monitoring Graphics',
  'Tracking Graphics',
  'Reporting Graphics',
  'Documentation Graphics',
  'Record Graphics',
  'Archive Graphics',
  'Storage Graphics',
  'Retrieval Graphics',
  'Access Graphics',
  'Security Graphics',
  'Privacy Graphics',
  'Confidentiality Graphics',
  'Protection Graphics',
  'Safeguard Graphics',
  'Defense Graphics',
  'Offense Graphics',
  'Attack Graphics',
  'Threat Graphics',
  'Risk Graphics',
  'Hazard Graphics',
  'Danger Graphics',
  'Warning Graphics',
  'Caution Graphics',
  'Alert Graphics',
  'Notice Graphics',
  'Announcement Graphics',
  'Declaration Graphics',
  'Statement Graphics',
  'Release Graphics',
  'Publication Graphics',
  'Distribution Graphics',
  'Circulation Graphics',
  'Broadcast Graphics',
  'Transmission Graphics',
  'Communication Graphics',
  'Message Graphics',
  'Information Graphics',
  'Data Graphics',
  'Knowledge Graphics',
  'Wisdom Graphics',
  'Insight Graphics',
  'Understanding Graphics',
  'Comprehension Graphics',
  'Learning Graphics',
  'Education Graphics',
  'Training Graphics',
  'Instruction Graphics',
  'Teaching Graphics',
  'Coaching Graphics',
  'Mentoring Graphics',
  'Tutoring Graphics',
  'Guiding Graphics',
  'Facilitating Graphics',
  'Enabling Graphics',
  'Empowering Graphics',
  'Supporting Graphics',
  'Assisting Graphics',
  'Helping Graphics',
  'Serving Graphics',
  'Caring Graphics',
  'Nurturing Graphics',
  'Developing Graphics',
  'Growing Graphics',
  'Evolving Graphics',
  'Transforming Graphics',
  'Changing Graphics',
  'Improving Graphics',
  'Enhancing Graphics',
  'Upgrading Graphics',
  'Advancing Graphics',
  'Progressing Graphics',
  'Moving Graphics',
  'Shifting Graphics',
  'Transitioning Graphics',
  'Migrating Graphics',
  'Transferring Graphics',
  'Converting Graphics',
  'Transforming Graphics',
  'Modifying Graphics',
  'Adjusting Graphics',
  'Adapting Graphics',
  'Customizing Graphics',
  'Personalizing Graphics',
  'Individualizing Graphics',
  'Specializing Graphics',
  'Focusing Graphics',
  'Targeting Graphics',
  'Aiming Graphics',
  'Directing Graphics',
  'Pointing Graphics',
  'Indicating Graphics',
  'Showing Graphics',
  'Displaying Graphics',
  'Presenting Graphics',
  'Demonstrating Graphics',
  'Illustrating Graphics',
  'Explaining Graphics',
  'Clarifying Graphics',
  'Simplifying Graphics',
  'Complicating Graphics',
  'Elaborating Graphics',
  'Detailing Graphics',
  'Specifying Graphics',
  'Defining Graphics',
  'Describing Graphics',
  'Characterizing Graphics',
  'Categorizing Graphics',
  'Classifying Graphics',
  'Organizing Graphics',
  'Structuring Graphics',
  'Arranging Graphics',
  'Ordering Graphics',
  'Sequencing Graphics',
  'Prioritizing Graphics',
  'Ranking Graphics',
  'Rating Graphics',
  'Scoring Graphics',
  'Measuring Graphics',
  'Quantifying Graphics',
  'Counting Graphics',
  'Calculating Graphics',
  'Computing Graphics',
  'Processing Graphics',
  'Handling Graphics',
  'Managing Graphics',
  'Controlling Graphics',
  'Operating Graphics',
  'Functioning Graphics',
  'Working Graphics',
  'Performing Graphics',
  'Executing Graphics',
  'Implementing Graphics',
  'Applying Graphics',
  'Using Graphics',
  'Utilizing Graphics',
  'Employing Graphics',
  'Deploying Graphics',
  'Activating Graphics',
  'Enabling Graphics',
  'Starting Graphics',
  'Beginning Graphics',
  'Initiating Graphics',
  'Launching Graphics',
  'Opening Graphics',
  'Commencing Graphics',
  'Inaugurating Graphics',
  'Establishing Graphics',
  'Creating Graphics',
  'Making Graphics',
  'Building Graphics',
  'Constructing Graphics',
  'Developing Graphics',
  'Designing Graphics',
  'Planning Graphics',
  'Preparing Graphics',
  'Setting Graphics',
  'Configuring Graphics',
  'Installing Graphics'
]