import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { PresentationGenerator } from '@/lib/presentation-generator'

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { title, content, slides, generateImages, imageStyle, theme } = await request.json()

    if (!title) {
      return NextResponse.json({ error: 'Title is required' }, { status: 400 })
    }

    console.log('Generating presentation:', title)
    console.log('Generate images:', generateImages)

    let buffer: Buffer

    if (slides && Array.isArray(slides)) {
      // Generate from structured slides
      const generator = new PresentationGenerator()
      buffer = await generator.generatePresentation({
        title,
        subtitle: 'Generated by ElimuNova AI',
        author: session.user.name || 'ElimuNova User',
        slides,
        theme: theme || 'education',
        generateImages: generateImages || false,
        imageStyle: imageStyle || 'educational'
      })
    } else if (content) {
      // Generate from text content
      buffer = await PresentationGenerator.generateFromAIContent(
        title,
        content,
        {
          generateImages: generateImages || false,
          imageStyle: imageStyle || 'educational',
          theme: theme || 'education'
        }
      )
    } else {
      return NextResponse.json(
        { error: 'Either slides or content is required' },
        { status: 400 }
      )
    }

    // Return the PowerPoint file
    return new NextResponse(buffer as any, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.pptx"`
      }
    })

  } catch (error) {
    console.error('Presentation generation error:', error)
    return NextResponse.json(
      { 
        error: 'Failed to generate presentation',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
