import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { PresentationGenerator } from '@/lib/presentation-generator'

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { 
      title, 
      subject, 
      grade, 
      topic, 
      duration, 
      objectives, 
      difficulty, 
      slideCount,
      content, 
      slides, 
      generateImages, 
      imageStyle, 
      theme 
    } = await request.json()

    // Handle both old format (title) and new format (subject/grade/topic)
    const presentationTitle = title || `${subject} - ${topic}` || 'AI Generated Presentation'
    
    if (!presentationTitle && !subject && !topic) {
      return NextResponse.json({ error: 'Title, subject, or topic is required' }, { status: 400 })
    }

    console.log('Generating AI presentation:', presentationTitle)
    console.log('Subject:', subject, 'Grade:', grade, 'Topic:', topic)
    console.log('Generate images:', generateImages !== false) // Default to true

    // If we have structured data (subject, grade, topic), generate AI content first
    if (subject && grade && topic && !slides && !content) {
      console.log('Generating AI content for presentation...')
      
      // Generate AI content using OpenRouter
      const aiContent = await generateAIPresentation({
        subject,
        grade,
        topic,
        duration: duration || 45,
        objectives: objectives || [],
        difficulty: difficulty || 'medium',
        slideCount: slideCount || 8
      })

      // Return the AI-generated content as JSON (not a file)
      return NextResponse.json({
        presentation: aiContent,
        title: presentationTitle,
        subject,
        grade,
        topic,
        slideCount: aiContent.split('\n').filter(line => line.includes('Slide')).length
      })
    }

    // If we have slides or content, generate the actual PowerPoint file
    let buffer: Buffer

    if (slides && Array.isArray(slides)) {
      // Generate from structured slides with enhanced generator
      const generator = new PresentationGenerator((progress, message) => {
        console.log(`Progress: ${progress}% - ${message}`)
      })
      
      // Convert slides to enhanced format
      const enhancedSlides = slides.map((slide, index) => ({
        id: slide.id || `slide-${index}`,
        title: slide.title,
        content: Array.isArray(slide.content) ? slide.content : [slide.content],
        notes: slide.speakerNotes || slide.notes,
        imagePrompt: slide.imagePrompt || slide.visualSuggestions?.join(', '),
        layout: slide.slideType === 'title' ? 'title' : 
                slide.slideType === 'image' ? 'image' :
                slide.slideType === 'chart' ? 'comparison' :
                slide.slideType === 'interactive' ? 'timeline' : 'content',
        order: slide.order || index + 1,
        metadata: {
          duration: Math.ceil((duration || 45) / (slides.length || 1)),
          difficulty: difficulty || 'medium'
        }
      }))

      buffer = await generator.generatePresentation({
        title: presentationTitle,
        subtitle: 'Generated by ElimuNova AI',
        author: session.user.name || 'ElimuNova User',
        subject: subject || 'Education',
        grade: grade || 'General',
        topic: topic || presentationTitle,
        duration: duration || 45,
        slides: enhancedSlides,
        theme: (theme as any) || 'education',
        generateImages: generateImages !== false,
        imageStyle: (imageStyle as any) || 'educational',
        options: {
          includeAnimation: false,
          includeTransitions: true,
          fontFamily: 'Calibri',
          primaryColor: theme === 'modern' ? '1A1A1A' : '2E5090',
          accentColor: theme === 'modern' ? '00BCD4' : '4472C4'
        }
      })
    } else if (content) {
      // Generate from text content with enhanced parsing
      buffer = await PresentationGenerator.generateFromAIContent(
        presentationTitle,
        content,
        {
          generateImages: generateImages !== false,
          imageStyle: imageStyle || 'educational',
          theme: theme || 'education',
          subject: subject || 'Education',
          grade: grade || 'General',
          duration: duration || 45
        }
      )
    } else {
      return NextResponse.json(
        { error: 'Either slides or content is required for file generation' },
        { status: 400 }
      )
    }

    // Return the PowerPoint file
    return new NextResponse(buffer as any, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${presentationTitle.replace(/[^a-z0-9]/gi, '_')}.pptx"`
      }
    })

  } catch (error) {
    console.error('Presentation generation error:', error)
    return NextResponse.json(
      { 
        error: 'Failed to generate presentation',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

// AI Content Generation Function
async function generateAIPresentation(params: {
  subject: string
  grade: string
  topic: string
  duration: number
  objectives: string[]
  difficulty: string
  slideCount: number
}): Promise<string> {
  try {
    const { subject, grade, topic, duration, objectives, difficulty, slideCount } = params

    const prompt = `Create a comprehensive educational presentation about "${topic}" for ${grade} ${subject} students.

Requirements:
- Duration: ${duration} minutes
- Number of slides: ${slideCount}
- Difficulty level: ${difficulty}
- Learning objectives: ${objectives.join(', ')}

CRITICAL: Each slide MUST include specific, detailed visual suggestions for AI image generation.

Please generate a detailed presentation with the following EXACT structure for each slide:

# Slide [number]: [Title]
**Content:**
[Detailed bullet points or paragraphs explaining the concept - make it engaging and age-appropriate]

**Speaker Notes:**
[Detailed notes for the teacher including explanations, examples, and teaching tips]

**Image Prompt:**
[REQUIRED: Specific, detailed prompt for AI image generation that will create an educational illustration for this slide. Be very specific about what should be shown, the style should be educational and appropriate for ${grade} students]

**Layout:**
[Choose: title, content, image, or split - this determines how the image will be positioned]

---

EXAMPLE FORMAT:
# Slide 1: Introduction to Photosynthesis
**Content:**
• Photosynthesis is how plants make their own food
• Plants use sunlight, water, and carbon dioxide
• This process produces oxygen that we breathe
• It happens mainly in the leaves of plants

**Speaker Notes:**
Start by asking students what they know about how plants get energy. Explain that unlike animals, plants don't eat food - they make it themselves through an amazing process called photosynthesis.

**Image Prompt:**
Educational diagram showing a green plant with labeled arrows pointing to sunlight from above, water being absorbed by roots from soil, and carbon dioxide entering through leaves, with oxygen bubbles coming out of leaves, cartoon style, bright colors, suitable for grade school students

**Layout:**
split

---

Make sure to:
1. Start with an engaging title slide with a welcoming image
2. Include clear learning objectives slide with educational icons
3. Break down complex concepts into digestible parts with supporting visuals
4. Provide practical examples relevant to ${grade} students with real-world images
5. Include interactive elements or questions with engaging illustrations
6. End with a summary slide that reinforces key concepts with a comprehensive visual
7. Make content age-appropriate for ${grade} level
8. EVERY slide must have a detailed "Image Prompt" for AI image generation
9. Choose appropriate "Layout" for each slide (title, content, image, split)
10. Make image prompts specific, educational, and appropriate for the grade level

Generate exactly ${slideCount} slides with this format. Each slide MUST have an Image Prompt and Layout specified.`

    // Use OpenRouter AI to generate the content
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'X-Title': 'ElimuNova AI Presentation Generator'
      },
      body: JSON.stringify({
        model: 'anthropic/claude-3.5-sonnet',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: 4000,
        temperature: 0.7
      })
    })

    if (!response.ok) {
      throw new Error(`OpenRouter API error: ${response.status}`)
    }

    const data = await response.json()
    const generatedContent = data.choices[0]?.message?.content

    if (!generatedContent) {
      throw new Error('No content generated from AI')
    }

    console.log('AI presentation generated successfully')
    return generatedContent

  } catch (error) {
    console.error('AI generation error:', error)
    // Fallback content if AI fails
    return generateFallbackPresentation(params)
  }
}

// Fallback presentation generator
function generateFallbackPresentation(params: {
  subject: string
  grade: string
  topic: string
  slideCount: number
}): string {
  const { subject, grade, topic, slideCount } = params

  let content = `# Slide 1: ${topic}
**Content:**
Welcome to our lesson on ${topic}
This presentation will help you understand the key concepts

**Speaker Notes:**
Introduce the topic and engage students with a question about their prior knowledge

**Visual Suggestions:**
Title slide with relevant subject imagery

---

# Slide 2: Learning Objectives
**Content:**
By the end of this lesson, you will be able to:
• Understand the main concepts of ${topic}
• Apply knowledge in practical situations
• Explain key terms and processes

**Speaker Notes:**
Review objectives with students and explain what they will learn

**Visual Suggestions:**
Bulleted list with icons for each objective

---`

  // Generate additional slides
  for (let i = 3; i <= slideCount - 1; i++) {
    content += `
# Slide ${i}: Key Concept ${i - 2}
**Content:**
Important information about ${topic}
• Key point 1
• Key point 2
• Key point 3

**Speaker Notes:**
Explain this concept clearly with examples relevant to ${grade} students

**Visual Suggestions:**
Diagrams or images that illustrate the concept

---`
  }

  // Summary slide
  content += `
# Slide ${slideCount}: Summary
**Content:**
Let's review what we learned about ${topic}:
• Main concept 1
• Main concept 2
• Main concept 3

**Speaker Notes:**
Summarize key points and check for understanding

**Visual Suggestions:**
Summary graphic with key takeaways

---`

  return content
}
