import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { PresentationGenerator } from '@/lib/presentation-generator'

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { title, content, format = 'pptx' } = await request.json()

    if (!title) {
      return NextResponse.json({ error: 'Title is required' }, { status: 400 })
    }

    console.log('Exporting PowerPoint:', title, 'Format:', format)

    let buffer: Buffer

    if (format === 'pdf') {
      // For PDF export, we'll generate PPTX first then convert (simplified approach)
      // In a real implementation, you might want to use a different library for PDF
      const generator = new PresentationGenerator()
      buffer = await generator.generatePresentation({
        title,
        subtitle: 'Generated by ElimuNova AI',
        author: session.user.name || 'ElimuNova User',
        slides: content.slides || [],
        theme: 'education',
        generateImages: false
      })
    } else {
      // Generate PPTX
      const generator = new PresentationGenerator()
      buffer = await generator.generatePresentation({
        title,
        subtitle: 'Generated by ElimuNova AI',
        author: session.user.name || 'ElimuNova User',
        slides: content.slides || [],
        theme: 'education',
        generateImages: true,
        imageStyle: 'educational'
      })
    }

    const contentType = format === 'pdf' 
      ? 'application/pdf'
      : 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    
    const fileExtension = format === 'pdf' ? 'pdf' : 'pptx'
    const filename = `${title.replace(/[^a-z0-9]/gi, '_')}.${fileExtension}`

    return new NextResponse(buffer as any, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`
      }
    })

  } catch (error) {
    console.error('PowerPoint export error:', error)
    return NextResponse.json(
      { 
        error: 'Failed to export PowerPoint',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}