import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

async function testCompletePresentationWithImages() {
  console.log('🎯 Testing Complete Presentation Generation with Images');
  console.log('='.repeat(60));

  // Mock AI-generated content (this is what the AI typically generates)
  const mockAIContent = `# Slide 1: Welcome to the Solar System
**Content:**
• Our solar system is an amazing place in space
• It has one star (the Sun) and eight planets
• Each planet is unique and special
• Let's explore this cosmic neighborhood together!

**Speaker Notes:**
Welcome students to this exciting journey through space! Start by asking them what they already know about space and planets. This will help gauge their prior knowledge and get them excited about learning more.

**Image Prompt:**
Colorful illustration of the solar system showing the Sun in the center with all eight planets orbiting around it, with their names labeled, cartoon style, bright colors, educational diagram suitable for grade 5 students, space background with stars

**Layout:**
title

---

# Slide 2: Learning Objectives
**Content:**
By the end of this lesson, you will be able to:
• Name all eight planets in our solar system
• Put the planets in order from the Sun
• Share one cool fact about each planet
• Understand why planets are different sizes and colors

**Speaker Notes:**
Review these objectives with students so they know what to expect. Emphasize that they'll become "space experts" by the end of the lesson. You might want to return to this slide at the end to check if objectives were met.

**Image Prompt:**
Educational infographic showing learning objectives with space-themed icons: telescope for identifying planets, numbered list for planet order, lightbulb for facts, and magnifying glass for understanding differences, colorful and engaging for elementary students

**Layout:**
content

---

# Slide 3: Meet Our Star - The Sun
**Content:**
• The Sun is the center of our solar system
• It's actually a giant ball of hot gas and fire
• The Sun gives us light and heat every day
• It's so big that over 1 million Earths could fit inside it!
• All planets orbit (go around) the Sun

**Speaker Notes:**
Explain that the Sun isn't actually "on fire" like a campfire, but it's so hot that gases glow. Help students understand the enormous size by comparing it to familiar objects. You might ask: "How do you think the Sun affects life on Earth?"

**Image Prompt:**
Bright, cheerful illustration of the Sun as the center of the solar system, showing its massive size compared to planets, with rays of light extending outward, educational cross-section showing it's made of gas, suitable for elementary students, warm colors

**Layout:**
split

---`;

  console.log('\n📄 Testing with Sample Presentation Content');
  console.log('='.repeat(50));
  
  // Parse the content
  const slides = parseAIContent(mockAIContent);
  
  console.log(`📊 Total slides parsed: ${slides.length}`);
  
  // Generate images for each slide
  console.log('\n🎨 Generating Images for Each Slide...');
  console.log('='.repeat(50));
  
  const slidesWithImages = [];
  
  for (let i = 0; i < slides.length; i++) {
    const slide = slides[i];
    console.log(`\n🖼️ Generating image for Slide ${i + 1}: "${slide.title}"`);
    
    if (slide.imagePrompt) {
      try {
        const imageUrl = await generateImage(slide.imagePrompt);
        if (imageUrl) {
          console.log('✅ Image generated successfully!');
          console.log(`📏 Image size: ${Math.round(imageUrl.length / 1024)} KB`);
          
          slidesWithImages.push({
            ...slide,
            imageUrl: imageUrl,
            hasGeneratedImage: true
          });
        } else {
          console.log('❌ Image generation failed');
          slidesWithImages.push({
            ...slide,
            hasGeneratedImage: false
          });
        }
      } catch (error) {
        console.log(`❌ Error generating image: ${error}`);
        slidesWithImages.push({
          ...slide,
          hasGeneratedImage: false
        });
      }
    } else {
      console.log('⚠️ No image prompt found');
      slidesWithImages.push({
        ...slide,
        hasGeneratedImage: false
      });
    }
    
    // Small delay between requests to avoid rate limiting
    await new Promise(resolve => setTimeout(resolve, 2000));
  }

  // Test PowerPoint generation with images
  console.log('\n📄 Testing PowerPoint Generation with Images...');
  console.log('='.repeat(50));
  
  try {
    const presentationData = {
      title: 'The Solar System - Grade 5',
      subtitle: 'Generated by ElimuNova AI',
      author: 'AI Teacher Assistant',
      slides: slidesWithImages.map(slide => ({
        title: slide.title,
        content: slide.content,
        speakerNotes: slide.speakerNotes,
        type: slide.layout || 'content',
        imageUrl: slide.imageUrl || null,
        imagePrompt: slide.imagePrompt
      }))
    };

    console.log('📊 Presentation structure:');
    console.log(`   Title: ${presentationData.title}`);
    console.log(`   Slides: ${presentationData.slides.length}`);
    console.log(`   Slides with images: ${presentationData.slides.filter(s => s.imageUrl).length}`);
    
    // Simulate PowerPoint generation (we can't actually create the file without the full system)
    console.log('\n✅ PowerPoint generation would include:');
    presentationData.slides.forEach((slide, index) => {
      console.log(`   Slide ${index + 1}: ${slide.title}`);
      console.log(`     Layout: ${slide.type}`);
      console.log(`     Has Image: ${slide.imageUrl ? 'Yes' : 'No'}`);
      console.log(`     Content Length: ${slide.content.length} chars`);
      console.log(`     Speaker Notes: ${slide.speakerNotes ? 'Yes' : 'No'}`);
    });

  } catch (error) {
    console.log(`❌ PowerPoint generation error: ${error}`);
  }

  // Final summary
  console.log('\n🎉 Complete Presentation Test Results');
  console.log('='.repeat(50));
  
  const successfulImages = slidesWithImages.filter(s => s.hasGeneratedImage).length;
  const totalSlides = slidesWithImages.length;
  
  console.log(`📊 Test Results:`);
  console.log(`   Total Slides: ${totalSlides}`);
  console.log(`   Images Generated: ${successfulImages}/${totalSlides}`);
  console.log(`   Success Rate: ${Math.round((successfulImages / totalSlides) * 100)}%`);
  console.log(`   Content Quality: ${slidesWithImages.every(s => s.title && s.content) ? 'Excellent' : 'Needs Review'}`);
  console.log(`   Speaker Notes: ${slidesWithImages.every(s => s.speakerNotes) ? 'Complete' : 'Incomplete'}`);
  
  if (successfulImages === totalSlides) {
    console.log('\n🎯 SYSTEM STATUS: FULLY OPERATIONAL! 🎯');
    console.log('Teachers can now generate complete presentations with AI-generated images!');
  } else if (successfulImages > 0) {
    console.log('\n⚡ SYSTEM STATUS: PARTIALLY OPERATIONAL');
    console.log('Some images generated successfully, system is working but may need optimization');
  } else {
    console.log('\n⚠️ SYSTEM STATUS: CONTENT ONLY');
    console.log('Content generation working, image generation needs attention');
  }

  return { slides: slidesWithImages, successRate: (successfulImages / totalSlides) * 100 };
}

// Parse AI content into structured slides
function parseAIContent(content: string) {
  const slides = [];
  const slideBlocks = content.split('---').filter(block => block.trim());
  
  for (const block of slideBlocks) {
    const lines = block.trim().split('\n');
    let slide: any = {};
    let currentSection = '';
    let currentContent = '';
    
    for (const line of lines) {
      if (line.startsWith('# Slide')) {
        slide.title = line.replace(/^# Slide \d+:\s*/, '').trim();
      } else if (line.startsWith('**Content:**')) {
        if (currentSection && currentContent) {
          slide[currentSection] = currentContent.trim();
        }
        currentSection = 'content';
        currentContent = '';
      } else if (line.startsWith('**Speaker Notes:**')) {
        if (currentSection && currentContent) {
          slide[currentSection] = currentContent.trim();
        }
        currentSection = 'speakerNotes';
        currentContent = '';
      } else if (line.startsWith('**Image Prompt:**')) {
        if (currentSection && currentContent) {
          slide[currentSection] = currentContent.trim();
        }
        currentSection = 'imagePrompt';
        currentContent = '';
      } else if (line.startsWith('**Layout:**')) {
        if (currentSection && currentContent) {
          slide[currentSection] = currentContent.trim();
        }
        currentSection = 'layout';
        currentContent = '';
      } else if (currentSection && line.trim()) {
        currentContent += line + '\n';
      }
    }
    
    // Add the last section
    if (currentSection && currentContent) {
      slide[currentSection] = currentContent.trim();
    }
    
    if (slide.title) {
      slides.push(slide);
    }
  }
  
  return slides;
}

// Generate image using Stability AI
async function generateImage(prompt: string): Promise<string | null> {
  try {
    console.log('🎨 Generating image with Stability AI...');
    
    const enhancedPrompt = `${prompt}, educational illustration, cartoon style, bright colors, child-friendly, high quality, detailed`;
    
    const response = await fetch('https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.STABILITY_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text_prompts: [
          {
            text: enhancedPrompt,
            weight: 1
          }
        ],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        samples: 1,
        steps: 30,
      }),
    });

    if (response.ok) {
      const data = await response.json();
      if (data.artifacts && data.artifacts[0]) {
        console.log('✅ Stability AI image generated successfully');
        return `data:image/png;base64,${data.artifacts[0].base64}`;
      }
    } else {
      const errorText = await response.text();
      console.log(`❌ Stability AI failed: ${response.status} - ${errorText.substring(0, 200)}`);
    }

    return null;

  } catch (error) {
    console.error('❌ Image generation error:', error);
    return null;
  }
}

// Run the test
if (require.main === module) {
  testCompletePresentationWithImages()
    .then((result) => {
      console.log(`\n🎯 Complete presentation test finished with ${result.successRate}% success rate!`);
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n💥 Test failed:', error);
      process.exit(1);
    });
}

export { testCompletePresentationWithImages };