'use client'

/**
 * InteractiveDiagram
 * Renders an educational diagram image with clickable "hotspot" markers over
 * specific labelled parts. Clicking a hotspot opens a panel with the part's
 * definition, function, and a deeper dive.
 *
 * Curriculum/locale agnostic — works for CBC, US, GED, Cambridge, etc. The
 * diagram image and its part data come from the parent (generated by AI, a
 * curated dataset, or stored in Supabase).
 *
 * Approach: overlay absolutely-positioned hotspots on the image using
 * percentage coordinates, so it scales responsively for any image size.
 */

import { useState, useRef, useCallback } from 'react'
import { X, BookOpen, Lightbulb, Target, ArrowRight } from 'lucide-react'

export interface DiagramPart {
  /** unique key for this part */
  id: string
  /** short label shown on the hotspot (e.g. "Stomach") */
  label: string
  /** x position as a percentage of image width (0–100) */
  x: number
  /** y position as a percentage of image height (0–100) */
  y: number
  /** one-line definition */
  definition: string
  /** what this part does */
  function?: string
  /** deeper explanation — may contain markdown-lite or plain text */
  deepDive?: string
  /** a fun fact or real-world connection */
  funFact?: string
}

interface InteractiveDiagramProps {
  imageUrl: string
  alt?: string
  parts: DiagramPart[]
  title?: string
  /** enable/disable the callout hints on hover */
  showLabels?: boolean
}

export function InteractiveDiagram({
  imageUrl,
  alt = 'interactive diagram',
  parts,
  title,
  showLabels = true,
}: InteractiveDiagramProps) {
  const [active, setActive] = useState<DiagramPart | null>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  const openPart = useCallback((part: DiagramPart) => setActive(part), [])
  const close = useCallback(() => setActive(null), [])

  return (
    <div className="my-5">
      {title && (
        <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-slate-500">
          {title} — click a number to explore
        </p>
      )}

      <div
        ref={containerRef}
        className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"
        role="region"
        aria-label={alt}
      >
        {/* The base diagram */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={imageUrl} alt={alt} className="w-full h-auto object-contain" />

        {/* Hotspot markers over mapped parts — percentage-based so they scale */}
        {parts.map((part) => (
          <button
            key={part.id}
            type="button"
            onClick={() => openPart(part)}
            aria-label={`${part.id}: ${part.label}`}
            className="group absolute -translate-x-1/2 -translate-y-1/2 focus:outline-none"
            style={{ left: `${part.x}%`, top: `${part.y}%` }}
          >
            {/* Pulsing dot */}
            <span className="relative flex h-6 w-6 items-center justify-center">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-blue-400 opacity-40" />
              <span className="relative inline-flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-[11px] font-bold text-white shadow-md ring-2 ring-white transition-transform group-hover:scale-110">
                {parts.indexOf(part) + 1}
              </span>
            </span>
            {/* Label on hover (desktop) */}
            {showLabels && (
              <span className="pointer-events-none absolute left-1/2 top-8 -translate-x-1/2 whitespace-nowrap rounded-md bg-slate-900/95 px-2 py-1 text-[10px] font-medium text-white opacity-0 shadow transition-opacity group-hover:opacity-100">
                {part.label}
              </span>
            )}
          </button>
        ))}

        {/* Hint when no part selected */}
        {parts.length > 0 && !active && (
          <div className="pointer-events-none absolute bottom-2 left-1/2 -translate-x-1/2 rounded-full bg-slate-900/70 px-3 py-1 text-[11px] text-white">
            👆 Tap a number to explore each part
          </div>
        )}
      </div>

      {/* ── Part details panel ── */}
      {active && (
        <div
          className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/50 p-4 sm:items-center"
          onClick={close}
          role="dialog"
          aria-modal="true"
          aria-label={`${active.label} details`}
        >
          <div
            className="w-full max-w-lg overflow-hidden rounded-2xl bg-white shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-start justify-between bg-gradient-to-r from-blue-600 to-indigo-600 px-5 py-4 text-white">
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-wider text-blue-200">
                  {title || 'Diagram part'}
                </p>
                <h3 className="text-lg font-extrabold leading-tight">{active.label}</h3>
              </div>
              <button
                onClick={close}
                className="rounded-full bg-white/20 p-1.5 transition-colors hover:bg-white/30"
                aria-label="Close"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Body */}
            <div className="max-h-[70vh] space-y-4 overflow-y-auto px-5 py-4">
              <div className="flex gap-2.5 rounded-xl border border-blue-100 bg-blue-50 p-3">
                <BookOpen className="h-4 w-4 shrink-0 text-blue-600 mt-0.5" />
                <div>
                  <p className="text-[11px] font-semibold uppercase tracking-wide text-blue-700">Definition</p>
                  <p className="text-sm text-slate-700">{active.definition}</p>
                </div>
              </div>

              {active.function && (
                <div className="flex gap-2.5 rounded-xl border border-emerald-100 bg-emerald-50 p-3">
                  <Target className="h-4 w-4 shrink-0 text-emerald-600 mt-0.5" />
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-wide text-emerald-700">Function</p>
                    <p className="text-sm text-slate-700">{active.function}</p>
                  </div>
                </div>
              )}

              {active.deepDive && (
                <div className="flex gap-2.5 rounded-xl border border-purple-100 bg-purple-50 p-3">
                  <Lightbulb className="h-4 w-4 shrink-0 text-purple-600 mt-0.5" />
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-wide text-purple-700">Deep dive</p>
                    <p className="whitespace-pre-line text-sm leading-relaxed text-slate-700">{active.deepDive}</p>
                  </div>
                </div>
              )}

              {active.funFact && (
                <div className="rounded-xl border border-amber-100 bg-amber-50 p-3">
                  <p className="text-sm text-amber-800">
                    <span className="font-bold">💡 Fun fact:</span> {active.funFact}
                  </p>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="border-t border-slate-100 px-5 py-3">
              <button
                onClick={close}
                className="flex w-full items-center justify-center gap-2 rounded-lg bg-slate-100 py-2 text-sm font-semibold text-slate-600 transition-colors hover:bg-slate-200"
              >
                Close <ArrowRight className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default InteractiveDiagram
